=== PerencevicZeljko/NRT_19_19/oglasi.dtd
<!ELEMENT oglasi (oglas)+>
<!ELEMENT oglas (kategorija, datumIsteka, cena, tekst, oznaka*, email+)>
<!ELEMENT kategorija (#PCDATA)>
<!ELEMENT datumIsteka (#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ELEMENT tekst (#PCDATA)>
<!ELEMENT oznaka (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email tip (privatni | sluzbeni) "privatni">
<!ATTLIST cena valuta CDATA "RSD">

=== PerencevicZeljko/NRT_19_19/oglasi.xml
<?xml version = "1.0" standalone="no"?>
<!DOCTYPE oglasi SYSTEM "oglasi.dtd">
<oglasi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="oglasi.xsd">
    <oglas>
        <kategorija>automobili</kategorija>
        <datumIsteka>2022-12-05</datumIsteka>
        <cena>15345</cena>
        <tekst>
            Prodajem Alfu za male pare, alfa roba!
        </tekst>
        <oznaka>Auto</oznaka>
        <oznaka>Alfa Romeo</oznaka>
        <oznaka>Povoljno</oznaka>
        <email tip="sluzbeni">povoljniRatko@yahoo.romeo</email>
    </oglas>
    <oglas> 
        <kategorija>automobili</kategorija>
        <datumIsteka>2022-09-22</datumIsteka>
        <cena>1200</cena>
        <tekst>
            Prodajem Lov Rajdera, kao nov!
        </tekst>
        <oznaka>Auto</oznaka>
        <oznaka>Lov</oznaka>
        <oznaka>Nov</oznaka>
        <oznaka>Garaza</oznaka>
        <email tip="privatni">izDisLov@yahoo.julija</email>
    </oglas>
    <oglas>
        <kategorija>stanovi</kategorija>
        <datumIsteka>2022-12-01</datumIsteka>
        <cena>39999</cena>
        <tekst>
            Stan na Beogradu na vodi sa pogledom na nekadasnji koncentracioni logor Sajmiste
        </tekst>
        <oznaka>Stan</oznaka>
        <oznaka>Beograd na vodi</oznaka>
        <oznaka>Beograd</oznaka>
        <email tip="privatni">prodoNisam@gmail.rs</email>
    </oglas>
</oglasi>
